export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const USERS_SIGN_UP_REQUEST = 'USERS_SIGN_UP_REQUEST';
export const USERS_SIGN_UP_SUCCESS = 'USERS_SIGN_UP_SUCCESS';
export const USERS_SIGN_UP_FAILURE = 'USERS_SIGN_UP_FAILURE';

export const SAVE_PIN_REQUEST = 'SAVE_PIN_REQUEST';
export const SAVE_PIN_SUCCESS = 'SAVE_PIN_SUCCESS';
export const SAVE_PIN_FAILURE = 'SAVE_PIN_FAILURE';

export const CREATE_BOARD_REQUEST = 'CREATE_BOARD_REQUEST';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAILURE = 'CREATE_BOARD_FAILURE';

export const LIST_USER_BOARDS_REQUEST = 'LIST_USER_BOARDS_REQUEST';
export const LIST_USER_BOARDS_SUCCESS = 'LIST_USER_BOARDS_SUCCESS';
export const LIST_USER_BOARDS_FAILURE = 'LIST_USER_BOARDS_FAILURE';
