export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const SAVE_PIN_REQUEST = 'SAVE_PIN_REQUEST';
export const SAVE_PIN_SUCCESS = 'SAVE_PIN_SUCCESS';
export const SAVE_PIN_FAILURE = 'SAVE_PIN_FAILURE';
